# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('order_no', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7')),
                ('img', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
                ('target_url', models.CharField(max_length=300, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('intro', models.TextField(blank=True, default='', verbose_name='\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('order_no', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7')),
                ('slug', models.CharField(default='', max_length=128, verbose_name='slug')),
                ('cover', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=128, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('content', models.TextField(default='', verbose_name='\u53cd\u9988\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u610f\u89c1\u53cd\u9988',
                'verbose_name_plural': '\u610f\u89c1\u53cd\u9988',
            },
        ),
    ]
