# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(default='', max_length=128, verbose_name='\u7ba1\u7406\u5458\u540d\u79f0')),
                ('ip', models.CharField(default='', max_length=128, verbose_name='\u7ba1\u7406\u5458IP')),
                ('admin_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u7ba1\u7406\u5458ID')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458\u767b\u5f55\u8bb0\u5f55',
                'verbose_name_plural': '\u7ba1\u7406\u5458\u767b\u5f55\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='JointVenture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(default='', max_length=128, verbose_name='\u540d\u79f0')),
                ('mobile', models.CharField(default='', max_length=128, verbose_name='\u7535\u8bdd')),
                ('address', models.CharField(default='', max_length=300, verbose_name='\u5730\u5740')),
                ('cover', models.CharField(default='', max_length=128, verbose_name='\u5934\u50cf')),
                ('intro', models.TextField(default='', verbose_name='\u7b80\u4ecb')),
                ('balance', models.FloatField(default=0, null=True, verbose_name='\u4f59\u989d')),
            ],
            options={
                'verbose_name': '\u5408\u4f5c\u4f01\u4e1a',
                'verbose_name_plural': '\u5408\u4f5c\u4f01\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='JointVentureAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('joint_venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.JointVenture', verbose_name='\u5408\u4f5c\u4f01\u4e1a')),
            ],
            options={
                'verbose_name': '\u5408\u4f5c\u4f01\u4e1a/\u7ba1\u7406\u5458\u8d26\u53f7',
                'verbose_name_plural': '\u5408\u4f5c\u4f01\u4e1a/\u7ba1\u7406\u5458\u8d26\u53f7',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('menu_str', models.TextField(blank=True, default='', verbose_name='\u83dc\u5355id')),
                ('menu_name_str', models.TextField(blank=True, default='', verbose_name='\u83dc\u5355\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6743\u9650\u7ec4',
                'verbose_name_plural': '\u6743\u9650\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('email', models.CharField(blank=True, default='', max_length=128, verbose_name='\u90ae\u7bb1')),
                ('user_name', models.CharField(default='', max_length=128, verbose_name='\u59d3\u540d')),
                ('nickname', models.CharField(default='', max_length=128, verbose_name='\u6635\u79f0')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='\u5bc6\u7801')),
                ('jwt_token', models.TextField(blank=True, default='', null=True, verbose_name='jwt_token')),
                ('background', models.CharField(blank=True, default='', max_length=255, verbose_name='\u80cc\u666f')),
                ('openid', models.CharField(default='', max_length=255, verbose_name='openid')),
                ('user_login_type', models.IntegerField(choices=[(1, '\u624b\u673a\u7528\u6237'), (2, '\u5fae\u4fe1\u7528\u6237'), (3, '\u5fae\u535a\u7528\u6237'), (4, 'qq')], default=1, verbose_name='\u7528\u6237\u6ce8\u518c\u7c7b\u578b')),
                ('gender', models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('bank_card', models.IntegerField(default=0, verbose_name='\u94f6\u884c\u5361')),
                ('id_card', models.CharField(blank=True, default='', max_length=128, verbose_name='\u8eab\u4efd\u8bc1\u4fe1\u606f')),
                ('id_card_picture', models.CharField(blank=True, default='', max_length=255, verbose_name='\u8eab\u4efd\u8bc1')),
                ('mobile', models.CharField(blank=True, default='', max_length=16, verbose_name='\u624b\u673a')),
                ('avatar', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='\u5934\u50cf')),
                ('wx_unionid', models.CharField(blank=True, default='', max_length=300, verbose_name='\u5fae\u4fe1id')),
                ('weibo_uid', models.CharField(blank=True, default='', max_length=300, verbose_name='\u5fae\u535aid')),
                ('qq_uid', models.CharField(blank=True, default='', max_length=300, verbose_name='qqid')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u5b57\u6bb5')),
                ('value', models.CharField(default='', max_length=100, verbose_name='\u503c')),
                ('detail', models.CharField(default='', max_length=100, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e',
                'verbose_name_plural': '\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('money', models.FloatField(default=0, null=True, verbose_name='\u91d1\u989d')),
                ('reason', models.CharField(default='', max_length=300, verbose_name='\u7406\u7531')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5904\u7406'), (1, '\u901a\u8fc7'), (2, '\u4e0d\u901a\u8fc7')], default=0, verbose_name='\u72b6\u6001')),
                ('join_tventure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.JointVenture', verbose_name='\u5408\u4f5c\u4f01\u4e1a')),
            ],
            options={
                'verbose_name': '\u63d0\u73b0',
                'verbose_name_plural': '\u63d0\u73b0',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u654f\u611f\u8bcd',
                'verbose_name_plural': '\u654f\u611f\u8bcd',
            },
        ),
        migrations.AddField(
            model_name='advertising',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
        migrations.AddField(
            model_name='column',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
        migrations.AddField(
            model_name='jointventureaccount',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Permissions', verbose_name='\u6240\u5c5e\u6743\u9650\u7ec4'),
        ),
        migrations.AddField(
            model_name='jointventureaccount',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
