# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedroom',
            name='complete',
        ),
    ]
