# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingpicture',
            name='order_no',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7'),
        ),
    ]
