# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170714_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
