# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_bedroom_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='house_config',
            field=models.ManyToManyField(to='web.HouseConfig', verbose_name='\u623f\u95f4\u914d\u7f6e'),
        ),
    ]
