# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_housingpicture_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='intro',
            field=models.TextField(blank=True, default='', null=True, verbose_name='\u5367\u5ba4\u7b80\u4ecb'),
        ),
    ]
