# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('cover', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u623f\u5c4b\u5367\u5ba4',
                'verbose_name_plural': '\u623f\u5c4b\u5367\u5ba4',
            },
        ),
        migrations.CreateModel(
            name='HousingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('picture', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u623f\u5c4b\u56fe\u7247',
                'verbose_name_plural': '\u623f\u5c4b\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='HousingResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('cover', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
                ('hall', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5927\u5385\u56fe\u7247')),
                ('peripheral', models.TextField(blank=True, default='', null=True, verbose_name='\u914d\u5957\u8bbe\u65bd')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='\u623f\u5c4b\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u623f\u6e90\u53d1\u5e03',
                'verbose_name_plural': '\u623f\u6e90\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('order_no', models.IntegerField(default=0, verbose_name='\u6392\u5e8f\u53f7')),
                ('cover', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u57fa\u7840\u8bbe\u65bd',
                'verbose_name_plural': '\u57fa\u7840\u8bbe\u65bd',
            },
        ),
        migrations.AddField(
            model_name='housingresources',
            name='infrastructure',
            field=models.ManyToManyField(to='web.Infrastructure', verbose_name='\u57fa\u7840\u8bbe\u65bd'),
        ),
        migrations.AddField(
            model_name='housingpicture',
            name='housing_resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingResources', verbose_name='\u623f\u6e90'),
        ),
        migrations.AddField(
            model_name='bedroom',
            name='housing_resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingResources', verbose_name='\u623f\u6e90'),
        ),
    ]
