# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_bedroom_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('content', models.TextField(default='', verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('point', models.FloatField(default=0, null=True, verbose_name='\u8bc4\u5206')),
                ('housing_resources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingResources', verbose_name='\u623f\u6e90')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u623f\u6e90\u8bc4\u4ef7',
                'verbose_name_plural': '\u623f\u6e90\u8bc4\u4ef7',
            },
        ),
        migrations.CreateModel(
            name='HousingEvaluationPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('img', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
                ('housing_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingEvaluation', verbose_name='\u623f\u6e90\u8bc4\u4ef7')),
            ],
            options={
                'verbose_name': '\u623f\u6e90\u8bc4\u4ef7',
                'verbose_name_plural': '\u623f\u6e90\u8bc4\u4ef7',
            },
        ),
    ]
