# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170716_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_card',
        ),
    ]
