# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_housingevaluation_housingevaluationpicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HousingEvaluationPicture',
            new_name='HousingEvaluationImg',
        ),
        migrations.AlterModelOptions(
            name='housingevaluationimg',
            options={'verbose_name': '\u623f\u6e90\u8bc4\u4ef7\u56fe\u7247', 'verbose_name_plural': '\u623f\u6e90\u8bc4\u4ef7\u56fe\u7247'},
        ),
    ]
