# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180217_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingevaluation',
            name='niming',
            field=models.IntegerField(default=0, verbose_name='\u533f\u540d'),
        ),
    ]
