# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170822_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='area',
            field=models.FloatField(blank=True, default=0, verbose_name='\u9762\u79ef'),
        ),
        migrations.AddField(
            model_name='bedroom',
            name='complete',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u914d\u5957'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='bus',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u516c\u4ea4'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='buy',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u8d2d\u7269'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='category',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u623f\u5c4b\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='community',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5c0f\u533a\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='deposit',
            field=models.IntegerField(choices=[(0, '\u62bc\u4e00\u4ed8\u4e09'), (1, '\u62bc\u4e00\u4ed8\u4e00')], default=0, verbose_name='\u62bc\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='direction',
            field=models.IntegerField(choices=[(0, '\u4e1c'), (1, '\u5357'), (2, '\u897f'), (3, '\u5317')], default=0, verbose_name='\u697c\u5c42\u671d\u5411'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='layer',
            field=models.IntegerField(default=0, verbose_name='\u5c42\u6570'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='lease',
            field=models.IntegerField(choices=[(0, '\u6574\u79df'), (1, '\u5408\u79df')], default=0, verbose_name='\u79df\u8d41\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='sitting_room',
            field=models.IntegerField(choices=[(0, '\u6709'), (1, '\u65e0')], default=0, verbose_name='\u6709\u65e0\u5ba2\u5385'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='sitting_room_area',
            field=models.FloatField(blank=True, default=0, verbose_name='\u5ba2\u5385\u9762\u79ef'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='sitting_room_complete',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5ba2\u5385\u914d\u5957'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='subway',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u5730\u94c1'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='total_layer',
            field=models.IntegerField(default=0, verbose_name='\u603b\u5c42\u6570'),
        ),
    ]
