# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170826_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employe',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='\u5de5\u4f5c\u5355\u4f4d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='\u52a8\u6001\u7801'),
        ),
    ]
