# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171004_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_card_status',
            field=models.IntegerField(choices=[(0, '\u672a\u8ba4\u8bc1'), (1, '\u5df2\u8ba4\u8bc1')], default=1, verbose_name='\u8eab\u4efd\u8ba4\u8bc1\u4fe1\u606f'),
        ),
    ]
