# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-04 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_profile_id_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birbath',
            field=models.DateField(default=datetime.date.today, verbose_name='\u751f\u65e5'),
        ),
    ]
