# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180306_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthousemeet',
            name='comp_meet_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 23, 9, 49, 901166), verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='renthousemeet',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5f85\u770b\u623f'), (1, '\u5df2\u770b\u623f')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
