# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-06 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20171006_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresources',
            name='bet',
            field=models.FloatField(default=0, verbose_name='\u62bc'),
        ),
        migrations.AlterField(
            model_name='housingresources',
            name='pay',
            field=models.FloatField(default=0, verbose_name='\u4ed8'),
        ),
    ]
