# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-06 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20171006_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingCertificatePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('picture', models.CharField(blank=True, default='', max_length=1024, verbose_name='\u56fe\u7247')),
                ('housing_resources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingResources', verbose_name='\u623f\u6e90')),
            ],
            options={
                'verbose_name': '\u623f\u5c4b\u623f\u4ea7\u8bc1\u56fe\u7247',
                'verbose_name_plural': '\u623f\u5c4b\u623f\u4ea7\u8bc1\u56fe\u7247',
            },
        ),
    ]
