# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180314_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthousemeet',
            name='comp_meet_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 0, 8, 2, 274825), verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
