# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_housingcertificatepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingResourcesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order_num', models.CharField(blank=True, default='', max_length=128, verbose_name='\u552f\u4e00\u8ba2\u5355\u53f7')),
                ('total_fee', models.FloatField(blank=True, default=0, verbose_name='\u603b\u8ba1\u91d1\u989d')),
                ('real_fee', models.FloatField(blank=True, default=0, verbose_name='\u5b9e\u9645\u4ed8\u6b3e')),
                ('pay_way', models.IntegerField(choices=[(1, '\u652f\u4ed8\u5b9dPC\u7f51\u7ad9\u652f\u4ed8'), (2, '\u5fae\u4fe1App\u652f\u4ed8'), (3, '\u652f\u4ed8\u5b9d\u79fb\u52a8\u652f\u4ed8'), (4, '\u652f\u4ed8\u5b9d\u624b\u673a\u7f51\u7ad9\u652f\u4ed8')], default=0, verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('pay_time', models.DateTimeField(auto_now=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('charge_id', models.CharField(blank=True, default='', max_length=300, verbose_name='ping++\u652f\u4ed8id')),
                ('status', models.IntegerField(choices=[(0, '\u5f85\u4e0b\u5355'), (1, '\u7b49\u5f85\u4ed8\u6b3e'), (2, '\u4ed8\u6b3e\u6210\u529f'), (3, '\u8ba2\u5355\u53d6\u6d88'), (4, '\u5df2\u5b8c\u6210'), (5, '\u9000\u6b3e\u7533\u8bf7\u4e2d'), (6, '\u9000\u6b3e\u4e2d'), (7, '\u9000\u6b3e\u6210\u529f')], default=0, verbose_name='\u72b6\u6001')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u623f\u6e90\u8ba2\u5355',
                'verbose_name_plural': '\u53d1\u5e03\u623f\u6e90\u8ba2\u5355',
            },
        ),
    ]
