# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_housingresourcesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='detail',
        ),
        migrations.AddField(
            model_name='setting',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='housingresourcesorder',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
