# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 10:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_auto_20180314_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingResourcesMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('meet_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('comp_meet_time', models.DateTimeField(default=datetime.datetime(2018, 3, 14, 10, 26, 58, 413373), verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(0, '\u5f85\u770b\u623f'), (1, '\u5df2\u770b\u623f')], default=0, verbose_name='\u72b6\u6001')),
                ('housing_resources', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.HousingResources', verbose_name='\u623f\u6e90\u53d1\u5e03')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u623f\u6e90\u9884\u7ea6',
                'verbose_name_plural': '\u623f\u6e90\u9884\u7ea6',
            },
        ),
        migrations.AlterField(
            model_name='renthousemeet',
            name='comp_meet_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 10, 26, 58, 407427), verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
