# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20180314_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresourcesmeet',
            name='comp_meet_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='renthousemeet',
            name='comp_meet_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u5df2\u9884\u7ea6\u65f6\u95f4'),
        ),
    ]
