# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20171008_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresourcesorder',
            name='pay_way',
            field=models.IntegerField(choices=[(0, '\u652f\u4ed8\u5b9dPC\u7f51\u7ad9\u652f\u4ed8'), (1, '\u5fae\u4fe1App\u652f\u4ed8'), (2, '\u652f\u4ed8\u5b9d\u79fb\u52a8\u652f\u4ed8'), (3, '\u652f\u4ed8\u5b9d\u624b\u673a\u7f51\u7ad9\u652f\u4ed8')], default=0, verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='housingresourcesorder',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
