# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20180314_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthouse',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='\u624b\u673a'),
        ),
    ]
