# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20180321_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mobile', models.CharField(default='', max_length=300, verbose_name='\u624b\u673a\u53f7')),
                ('content', models.CharField(default='', max_length=300, verbose_name='\u9700\u6c42')),
            ],
            options={
                'verbose_name': '\u79df\u623f\u9700\u6c42',
                'verbose_name_plural': '\u79df\u623f\u9700\u6c42',
            },
        ),
    ]
