# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_housingresources_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresources',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u4e0b\u7ebf'), (2, '\u4e0a\u7ebf')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
