# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20171010_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingresources',
            name='area',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u533a'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='city',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u5e02'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='month_rent',
            field=models.FloatField(default=0, verbose_name='\u6708\u79df\u91d1'),
        ),
        migrations.AddField(
            model_name='housingresources',
            name='province',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u7701'),
        ),
    ]
