# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20171105_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('rent', models.IntegerField(choices=[(0, '0-500'), (1, '500-1000'), (2, '1000-1500'), (3, '1500-2000'), (4, '2000-2500'), (5, '2500-3000'), (6, '3000-3500'), (7, '3500-4000'), (8, '4000\u4ee5\u4e0a')], default=0, verbose_name='\u79df\u91d1')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='\u8865\u5145\u8bf4\u660e')),
                ('date', models.DateField(verbose_name='\u6700\u8fdf\u5165\u4f4f\u65e5\u671f')),
                ('lease', models.IntegerField(choices=[(0, '\u5408\u79df'), (1, '\u6574\u79df')], default=0, verbose_name='\u79df\u8d41\u65b9\u5f0f')),
                ('name', models.CharField(default='', max_length=32, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='\u624b\u673a')),
                ('infrastructure', models.ManyToManyField(to='web.Infrastructure', verbose_name='\u57fa\u7840\u8bbe\u65bd')),
            ],
            options={
                'verbose_name': '\u6c42\u7ec4\u53d1\u5e03',
                'verbose_name_plural': '\u6c42\u7ec4\u53d1\u5e03',
            },
        ),
    ]
