# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_housingdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingdemand',
            name='area',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u533a'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='city',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u5e02'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='province',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u7701'),
        ),
    ]
