# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20171121_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingdemand',
            name='accept',
            field=models.IntegerField(choices=[(0, '\u767d\u9886'), (1, '\u5b66\u751f'), (2, '\u4e0d\u9650')], default=0, null=True, verbose_name='\u80fd\u63a5\u53d7\u7684\u5408\u79df\u5bf9\u8c61'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='female_count',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], default=0, null=True, verbose_name='\u5973\u6027\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='male_count',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], default=0, null=True, verbose_name='\u7537\u6027\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='relationship',
            field=models.IntegerField(choices=[(0, '\u670b\u53cb'), (1, '\u60c5\u4fa3'), (2, '\u540c\u5b66'), (3, '\u4eb2\u621a'), (4, '\u964c\u751f\u4eba'), (5, '\u5176\u4ed6')], default=0, null=True, verbose_name='\u5173\u7cfb'),
        ),
        migrations.AddField(
            model_name='housingdemand',
            name='total_count',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6')], default=0, null=True, verbose_name='\u603b\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='housingdemand',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='\u624b\u673a'),
        ),
    ]
