# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20171122_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HousingDemand',
            new_name='RentHouse',
        ),
    ]
