# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20171122_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthouse',
            name='audit_status',
            field=models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5ba1\u6838\u4e0d\u901a\u8fc7'), (2, '\u5ba1\u6838\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='renthouse',
            name='status',
            field=models.IntegerField(choices=[(0, ''), (1, '\u4e0b\u7ebf'), (2, '\u4e0a\u7ebf')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
