# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_renthouse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingcertificatepicture',
            name='housing_resources',
        ),
        migrations.AddField(
            model_name='housingresources',
            name='house_pcover',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u623f\u4ea7\u8bc1'),
        ),
        migrations.DeleteModel(
            name='HousingCertificatePicture',
        ),
    ]
