# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_renthouse_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renthouse',
            options={'verbose_name': '\u6c42\u79df\u53d1\u5e03', 'verbose_name_plural': '\u6c42\u79df\u53d1\u5e03'},
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='accept',
            field=models.IntegerField(blank=True, choices=[(0, '\u767d\u9886'), (1, '\u5b66\u751f'), (2, '\u4e0d\u9650')], default=0, null=True, verbose_name='\u80fd\u63a5\u53d7\u7684\u5408\u79df\u5bf9\u8c61'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='date',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u6700\u8fdf\u5165\u4f4f\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='\u8865\u5145\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='female_count',
            field=models.IntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], default=0, null=True, verbose_name='\u5973\u6027\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='male_count',
            field=models.IntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], default=0, null=True, verbose_name='\u7537\u6027\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='relationship',
            field=models.IntegerField(blank=True, choices=[(0, '\u670b\u53cb'), (1, '\u60c5\u4fa3'), (2, '\u540c\u5b66'), (3, '\u4eb2\u621a'), (4, '\u964c\u751f\u4eba'), (5, '\u5176\u4ed6')], default=0, null=True, verbose_name='\u5173\u7cfb'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='rent',
            field=models.IntegerField(choices=[(0, '0-500'), (1, '500-1000'), (2, '1000-1500'), (3, '1500-2000'), (4, '2000-2500'), (5, '2500-3000'), (6, '3000-3500'), (7, '3500-4000'), (8, '4000\u4ee5\u4e0a'), (9, '\u4e0d\u9650')], default=0, verbose_name='\u79df\u91d1'),
        ),
        migrations.AlterField(
            model_name='renthouse',
            name='total_count',
            field=models.IntegerField(blank=True, choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6')], default=0, null=True, verbose_name='\u603b\u4eba\u6570'),
        ),
    ]
