# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20171219_0139'),
        ('web', '0028_auto_20171219_1526'),
    ]

    operations = [
    ]
